### ISSUE TITLE
Discussion: Should URLs be translated too?

### ISSUE THREAD

**Issue by joostdecock** [freesewing/website#100]
This issue was raised by @Kittycatou and I think it's a valid point, so I'm opening a discussion here.

Essentially, the question is whether or not we should translate URLs. For example:
 
 - `/en/patrons/join`
   - `/fr/patrons/join` => Just change the language prefix
   - `/fr/mecenes/rejoindre` => Translate the URL itself

The first option is how it works now. The second option would require us to change the way different languages are resolved. Essentially, we need to find a way for the system to know that `/en/patrons/join` and `/fr/mecenes/rejoindre` are the same thing. Not impossible, but it would require some work.

You opinions/preferences are welcome :)

**Comment by Kittycatou** [comment]
I personally think that we should keep it simple and just change the language prefix.
As a user, I'm more interested by the contents than the URL. It's already super cool to have the option to browse the website in different languages.

**Comment by kristinruben** [comment]
I haven't seen a ton of precedent for translated path names, but I am admittedly an English speaker ;)

**Comment by joostdecock** [comment]
> I personally think that we should keep it simple and just change the language prefix.

That certainly would be less work :)

I'll keep this open a while longer in case others want to weigh in. If not, I'll close it and we'll stick to how things are.

**Comment by woutervdub** [comment]
I don't think there are that many people that use URLs directly. You search, you bookmark, you click on some link you've received through some means, but you hardly ever type a link directly in my experience. I think the extra complexity does not really add much. And it does obscure that different versions of the same article are actually translations of the same thing. 

If a language version of an article doesn't exist, how is the URL now named? Does a /<lang>/patrons/join exist, and points to the English version, or is the /en/ version used until the page has been translated?

**Comment by joostdecock** [comment]
> If a language version of an article doesn't exist, how is the URL now named?

All pages are available in all languages. For example, if you go to https://beta.freesewing.org/fr/docs/about the content itself is English (because it does not exists in French). However, the menus, the header, the footer, and everything else is still in French. There's just the English content with a message (in French) that a French translation is not available, thus we show the English version.

**Comment by woutervdub** [comment]
So you would have /fr/patrons/join until someone decides to translate it, and then it would become /fr/mecenes/rejoindre. At which point the old URL would no longer work unless you would be prepared to have both URLs available. Or you would have to translate all URLs the moment you decide to make 'fr' a language, just to avoid having /fr/patrons/join exist in the first place. This seems to me to add a bunch of complexity that doesn't really add too much convenience to the user.

**Comment by joostdecock** [comment]
Ok
