### ISSUE TITLE
Add a redux store and some getting/setting state functionality

### ISSUE THREAD

**Issue by joostdecock** [freesewing/website#18]
There's some [example code here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux) for using Redux. 

This is one of those things that is really trivial to do in Vue, yet is a complete pain in the hole in React for reasons that I just can't wrap my head around.

**Comment by sophiekoonin** [comment]
I can do this if you want!

**Comment by joostdecock** [comment]
Please knock yourself out :)  Once we hook up the frontend to the backend API, we'll need this to handle application state.

**Comment by sophiekoonin** [comment]
Hey @joostdecock, will you be using Gatsby's server-side rendering at all?

**Comment by joostdecock** [comment]
We're pushing a static build to Netlify. So when you land on a page, you get what is essentially an SSR render. That will bootstrap the SPA, so after that, things are rendered on the client.

We don't render server side after the initial build.

So yes and no? 🤔

**Comment by sophiekoonin** [comment]
<3 Netlify! 

Right, I've got a basic Redux store installed, but no reducers yet. next question: when you say "some getting/setting state functionality" what exactly do you mean? This could mean quite a few things! 

If you can tell me what shape you want your state to be (at least for now) and what will trigger updates to the state/what will read from the state, I can implement that.

**Comment by joostdecock** [comment]
This is my first react app, and I am in *fake it 'till you make it* mode. I'd like to have a solution that makes sense. I have no idea at this point what that will look like :)

What I'm saying is: I don't know the answers. I'll can probably figure them out as I go along, but I'm just as happy with you making choices and then that's how it will be.

**Comment by sophiekoonin** [comment]
I can't really implement any reducers if I don't know what data you want in your store, so I guess I'll leave it as it is, with the basic framework in. You will then be able to add the actions and reducers that you need. I recommend having a good look at the [redux docs](https://redux.js.org/introduction) as they're really helpful. I'm also happy to answer any questions you might have.

**Comment by joostdecock** [comment]
That's great. Thanks a lot. I might very well pick you brain when I get around to this.
I'm closing this in favor of more specific issues down the line.
