### ISSUE TITLE
Please allow sign-in with Google auth

### ISSUE THREAD

**Issue by wt** [freesewing/website#78]
Hi there, it would be super awesome if I could tie my Google account to my account for freesewing so that I could login without yet another password.

Here's a link for info: https://developers.google.com/identity/sign-in/web/sign-in

Other SSOs would also probably be handy.

BTW, I really love the site. Thanks for putting this together.

**Comment by joostdecock** [comment]
This issue was auto-closed after deploying the code that implements it yesterday. However, I still had to configure the API access for Google and Github, but that's also done now.

Long story short, you can now signup/login with your Github or Google account.
